<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.xbstar</groupId>
    <artifactId>project</artifactId>
    <version>1.1.1</version>
    <packaging>pom</packaging>
    <!-- 配置应用参数-->
    <name>中科西北星模板工程</name>
    <description>中科西北星内部创建Maven项目的快速依赖模板</description>
    <url>https://github.com/xbstar/project</url>

    <!-- 配置项目模块信息-->
    <modules>
        <module>spring</module>
        <module>flink</module>
<!--        <module>cgreact</module>-->
    </modules>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <version>2.5.6</version>
        </dependency>
    </dependencies>

    <!-- 部署到中央仓库的部署配置-->
    <profiles>
        <profile>
            <id>deploy-to-XBX152</id>
            <distributionManagement>
                <repository>
                    <id>XBX152</id>
                    <url>http://192.168.1.152:9999/repository/CGMAVEN/</url>
                </repository>
            </distributionManagement>
        </profile>
        <profile>
            <id>deploy-to-MavenCentral</id>
            <distributionManagement>
                <repository>
                    <id>MavenCentral</id>
                    <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
                </repository>
            </distributionManagement>
        </profile>
    </profiles>

    <!-- 配置开源协议 -->
    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <!-- 配置开发者信息 -->
    <developers>
        <developer>
            <name>ChenGuang</name>
            <email>cheng@ciotc.org</email>
            <organization>中科西北星</organization>
            <organizationUrl>http://www.zkxbx.com</organizationUrl>
        </developer>
    </developers>
    <!-- 配置项目源码信息-->
    <scm>
        <connection>scm:git:git://github.com/xbstar/project.git</connection>
        <developerConnection>scm:git:ssh://github.com:xbstar/project.git</developerConnection>
        <url>https://github.com/xbstar/project</url>
    </scm>
    <!-- 项目打包时进行GPG签名的插件配置-->
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>site</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
