deliver.package=com.test.adbt
deliver.source=Deliver/src
deliver.jdbc=jdbc:mysql://192.168.1.160:3306/zwys
deliver.username=root
deliver.password=tobeno1
minio.server=http://10.233.37.215:9000
minio.username=root
minio.password=tobeno1@





