apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION}
  annotations:
    kubesphere.io/description: ${DESCRIPTION}
spec:
  selector:
    app: ${APPLICATION}
  ports:
    - name: http
      port: ${APPPORT}
      protocol: TCP
      targetPort: ${APPPORT}
  sessionAffinity: None
  type: ClusterIP
