<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.xbstar</groupId>
    <artifactId>minio</artifactId>
    <version>1.1.1</version>
    <name>MinIO</name>
    <packaging>jar</packaging>
    <description>西北星整合MinIO对象存储框架</description>
    <url>https://github.com/xbstar/project</url>

    <properties>
        <java.version>11</java.version>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <!-- 底层依赖XBStarUtils-->
        <dependency>
            <groupId>io.github.xbstar</groupId>
            <artifactId>utils</artifactId>
            <version>1.1.1</version>
            <scope>compile</scope>
        </dependency>
        <!-- Spring环境会自己带-->
        <dependency>
            <groupId>io.github.xbstar</groupId>
            <artifactId>spring</artifactId>
            <version>1.1.1</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src</sourceDirectory>
    </build>
</project>
